{% set name = "pymeasure" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMeasure-{{ version }}.tar.gz
  sha256: 6c6f101407fef1a2218c63f333d0eeeb3c5cf614433d3a1331480988022ad520

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - pytest-runner
  run:
    - python >=3.8
    - numpy >=1.6.1
    - pandas >=0.14
    - pint
    - pyqtgraph >=0.12
    - pyserial >=2.7
    - pyvisa >=1.8

test:
  imports:
    - pymeasure
    - pymeasure.adapters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pymeasure/pymeasure
  license: MIT
  license_file: LICENSE.txt
  summary: Scientific measurement library for instruments, experiments, and live-plotting.
  description: |
    PyMeasure makes scientific measurements easy to set up and run. The package contains a 
    repository of instrument classes and a system for running experiment procedures, 
    which provides graphical interfaces for graphing live data and managing queues of 
    experiments. Both parts of the package are independent, and when combined provide 
    all the necessary requirements for advanced measurements with only limited coding.
  doc_url: http://pymeasure.readthedocs.io
  dev_url: https://github.com/pymeasure/pymeasure

extra:
  recipe-maintainers:
    - melund
    - ddale
    - cjermain
    - bilderbuchi
    - CasperSchippers
