schema_version: 1

context:
  name: pymeasure
  version: 0.15.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 2867db427948ac3487b365c64ed5805507899808b08450285327f21e72a36ae1

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm >=8.1.0
  run:
    - python >=${{ python_min }}
    - numpy >=1.6.1,<3
    - pandas >=0.14,<3
    - pint
    - pyqtgraph >=0.12
    - pyserial >=2.7
    - pyvisa >=1.9

tests:
  - python:
      imports:
        - pymeasure
        - pymeasure.adapters
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - pip check

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Scientific measurement library for instruments, experiments, and live-plotting.
  description: |
    PyMeasure makes scientific measurements easy to set up and run. The package contains a
    repository of instrument classes and a system for running experiment procedures,
    which provides graphical interfaces for graphing live data and managing queues of
    experiments. Both parts of the package are independent, and when combined provide
    all the necessary requirements for advanced measurements with only limited coding.
  homepage: https://github.com/pymeasure/pymeasure
  repository: https://github.com/pymeasure/pymeasure
  documentation: http://pymeasure.readthedocs.io

extra:
  recipe-maintainers:
    - BenediktBurger
    - melund
    - ddale
    - cjermain
    - bilderbuchi
    - CasperSchippers
