appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: g2xkCziTWHY4zF0jtkB1qlTf7eOVj1CNzoSLcVyVRmv2cbVQDEJvA/1pnEeEKQhI1lpYZMajLGgmrRLeQsHXcKCSikn9t+pSm1UO9vV5f3MxrwEQfNhlATmeTgB03HH2cFbv0hLUZ9PfO5Yf1z9Cl5lXzz+JvzWbne0AaJmukhmiCwqo83lkqYgLDB8lPf01+SXlUI9vSDmM1ZeNGa12zXeKOFMs4VFHVjdU73Sp8mCXY/09HSuXAxMxmM02FpNoccOEDHsBOFuHnEB4te2iZFYjrrshOBC8WbFlqCWDd+TnBsljl/PWADQXbCG2Ivpgg1aMSC7rfhSTl+/84qyGPbsujYqiqsw7LLyafPQpx6woi0qtAHPdKF8V4I450ly58BWZng1aifrs7BMs3T//5VLNAbGzR1FfZAbr+6/dQyx/0jvFiyqf3t5nsbjIxYwKgHkYIGS9SFlXaRyrkgaH9M8GmMSrAznehzQqNb9FuXXMhFe8dAyi/5fF3zyBhyrTEeVkiN2mX5Fpz8YQrcOHyDxOVqlgYNEJ1l7WqDyBDJdahTJ4hDfbEaptBDuY+ZTxjK2Oxi699fktDeyNlJ9Hlcz/x9lWseyKi2II5XAs+x+WOQjxI3XLMkcWZBQ+P57BYgpKB5P8ThcYPojJ1FtJYVytmS7OGVHpvGpHP16LY08=}
provider:
  win: azure
conda_forge_output_validation: true
